from __future__ import annotations

import base64
import json
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4


PLACEHOLDER_PNG = (
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9WnPZX0AAAAASUVORK5CYII="
)


def make_run_id() -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    return f"{timestamp}_{uuid4().hex[:8]}"


def ensure_run_layout(base_dir: str | Path) -> Path:
    run_dir = Path(base_dir)
    for subdir in ("reports", "cleaned", "figures", "notebook", "summary"):
        (run_dir / subdir).mkdir(parents=True, exist_ok=True)
    return run_dir


def write_placeholder_png(path: str | Path) -> Path:
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(base64.b64decode(PLACEHOLDER_PNG))
    return output_path


def markdown_cell(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [source],
    }


def code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [source],
    }


def write_notebook(path: str | Path, cells: list[dict], metadata: dict | None = None) -> Path:
    notebook = {
        "cells": cells,
        "metadata": metadata or {},
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    notebook_path = Path(path)
    notebook_path.parent.mkdir(parents=True, exist_ok=True)
    with notebook_path.open("w", encoding="utf-8") as handle:
        json.dump(notebook, handle, ensure_ascii=False, indent=2)
    return notebook_path


def _read_json_artifact(path: str | Path) -> dict | list | None:
    artifact_path = Path(path)
    if not artifact_path.exists():
        return None
    with artifact_path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def render_notebook_from_artifacts(
    notebook_output_path: str | Path,
    summary_report_path: str | Path = "",
    profile_path: str | Path = "",
    correlation_path: str | Path = "",
    comparison_paths: list[str] | None = None,
    figure_paths: list[str] | None = None,
    decision_path: str | Path = "",
    dataset_description: str = "",
    chosen_strategy: dict | None = None,
) -> str:
    summary = _read_json_artifact(summary_report_path) if summary_report_path else {}
    profile = _read_json_artifact(profile_path) if profile_path else {}
    correlations = _read_json_artifact(correlation_path) if correlation_path else {}
    figures = figure_paths or []
    comparisons = comparison_paths or []
    chosen = chosen_strategy or {}
    decision_markdown = "No decision summary provided."
    if decision_path:
        decision_file = Path(decision_path)
        if decision_file.exists():
            decision_markdown = decision_file.read_text(encoding="utf-8")

    cells = [
        markdown_cell("# Data Quality Audit"),
        markdown_cell(dataset_description or "Dataset quality analysis run."),
        markdown_cell("## Summary"),
        markdown_cell(json.dumps(summary or {}, ensure_ascii=False, indent=2)),
        markdown_cell("## Profile"),
        markdown_cell(json.dumps(profile or {}, ensure_ascii=False, indent=2)),
        markdown_cell("## Correlations"),
        markdown_cell(json.dumps(correlations or {}, ensure_ascii=False, indent=2)),
        markdown_cell("## Figures"),
        markdown_cell("\n".join(f"- `{item}`" for item in figures) if figures else "No figures were generated."),
        markdown_cell("## Comparison Reports"),
        markdown_cell(
            "\n".join(f"- `{item}`" for item in comparisons) if comparisons else "No comparison reports were generated."
        ),
        markdown_cell("## Chosen Strategy"),
        markdown_cell(json.dumps(chosen, ensure_ascii=False, indent=2)),
        markdown_cell("## Decision"),
        markdown_cell(decision_markdown),
        code_cell("# Notebook artifact generated by ToolBasedDataQualityAgent\n"),
    ]
    return str(write_notebook(notebook_output_path, cells))


def render_notebook_from_context(notebook_output_path: str | Path, context: dict) -> str:
    summary = context.get("summary", {})
    figures = context.get("figures", [])
    comparisons = context.get("comparisons", [])
    chosen_strategy = context.get("chosen_strategy", {})
    decision_markdown = context.get("decision_markdown", "No decision summary provided.")

    cells = [
        markdown_cell("# Data Quality Audit"),
        markdown_cell(context.get("dataset_description", "Dataset quality analysis run.")),
        markdown_cell("## Summary"),
        markdown_cell(json.dumps(summary, ensure_ascii=False, indent=2)),
        markdown_cell("## Figures"),
        markdown_cell("\n".join(f"- `{item}`" for item in figures) if figures else "No figures were generated."),
        markdown_cell("## Comparison Reports"),
        markdown_cell(
            "\n".join(f"- `{item}`" for item in comparisons) if comparisons else "No comparison reports were generated."
        ),
        markdown_cell("## Chosen Strategy"),
        markdown_cell(json.dumps(chosen_strategy, ensure_ascii=False, indent=2)),
        markdown_cell("## Decision"),
        markdown_cell(decision_markdown),
        code_cell("# Notebook artifact generated by ToolBasedDataQualityAgent\n"),
    ]
    return str(write_notebook(notebook_output_path, cells))
